### ISSUE TITLE
A garbage collector is needed

### ISSUE THREAD

**Issue by PythonLinks** [mulle-objc/MulleObjC#13]
Hello
I am getting closer to using Mulle Objc. 
I will need a garbage collector.  

The basic idea is to build something like Erlang.  Lots of communicating sequential processes, each written in Python. 

Can you recommend a gargage collector?

Chris

**Comment by mulle-nat** [comment]
I can't recommend any, since I don't use them. For C languages I think [Boehm GC](https://www.hboehm.info/gc/) is the only choice.
